Cargo.lock
Cargo.toml
deny.toml
src/rpc.rs
src/rpc/client/blobs.rs
src/rpc/client/blobs/batch.rs
src/rpc/client/tags.rs

Try out the new simplified service mapping

refactor: use quic-rpc v0.15.0 and adapt code

---

Cargo.toml
src/lib.rs
src/net_protocol.rs
src/rpc.rs
src/rpc/client/blobs.rs

Add net_protocol feature and make some things private in rpc

feat!: add net_protocol feature

---

Cargo.lock
Cargo.toml
deny.toml
src/downloader.rs
src/net_protocol.rs
src/protocol.rs
src/rpc.rs
src/rpc/client.rs
src/rpc/client/blobs.rs
src/util/fs.rs

Add a mem rpc client just like in https://github.com/n0-computer/iroh-gossip/pull/7
Also make it possible to get tags from blobs so blobs is the "entry point" of the blobs client api.

feat: Add a lazily initialized in mem client for ffi etc.

---

Cargo.lock
Cargo.toml
examples/custom-protocol.rs
examples/hello-world-fetch.rs
examples/hello-world-provide.rs
examples/local-swarm-discovery.rs
src/lib.rs
src/net_protocol.rs
src/rpc/client/blobs.rs

This shows how to use `iroh` with `iroh-blobs`
We have to build our own node since there is no more standard iroh node.

examples: import examples from main repo

---

Cargo.lock
Cargo.toml
deny.toml
examples/custom-protocol.rs
examples/hello-world-fetch.rs
examples/hello-world-provide.rs
examples/local-swarm-discovery.rs
src/cli.rs
src/downloader.rs
src/downloader/get.rs
src/downloader/test.rs
src/get.rs
src/get/db.rs
src/get/error.rs
src/get/request.rs
src/net_protocol.rs
src/protocol.rs
src/provider.rs
src/rpc/client/blobs.rs
src/util/fs.rs

Updates the code use the renamed `iroh-net` and dependencies

feat: update to latest iroh

---

Cargo.lock
src/net_protocol.rs
tests/blobs.rs

This adds gc to blobs so it does not have to be driven externally. A big complication is that we want to have the ability to add exemptions to gc, e.g. from docs or willow.
So the gc is initially not running when the Blobs object is created. We have the ability to add exemption callbacks in this stage. Once the setup is done you can (but don't have to!) start the gc loop, at which point adding exemptions is no longer possible.

feat: Pluggable gc with exemptions

---

src/net_protocol.rs
src/store/fs/tables.rs

Add Blobs::builder and use it from Blobs::memory and Blobs::persistent
So we have the ability to use the builder when we have a store from outside.
none

feat: Add Blobs::builder and use it from Blobs::memory and Blobs::persistent

---

Cargo.toml
examples/transfer.rs
src/downloader/test.rs

Adds a simple example that basically rebuilds sendme, but simpler. No fancy clap interface, no progress bars, all in-memory blobs, copying stuff around needlessly.
But most importantly: It's very simple, just one function.
---
Also: I noticed there's an `example-iroh` feature that's enabled-by-default in blobs, which pulls in `clap`, `indicativ` and `console`. We probably don't want that in there, right?
---
I guess it would be nice to add some context about **"Why am I doing this?"**: I'm thinking of linking to this from the quickstart guide of a new iroh docs page.
None
Only that I removed the `example-iroh` feature from the default feature set.

docs: Add simple file transfer example

---

Cargo.toml
src/net_protocol.rs
tests/blobs.rs

also removes `rpc` from the default feature flags to reduce dependency load

fix!: make `net_protocol` feature work without `rpc`

---

Cargo.lock
Cargo.toml
deny.toml
examples/custom-protocol.rs
src/net_protocol.rs
src/rpc.rs
src/rpc/client/blobs.rs
tests/gc.rs

Update to new protocolhandler
Changes to the ProtocolHandler in iroh require this update. Unfortunately this also means a git dependency until we do another release.

feat: update to new protocolhandler

---

src/downloader.rs
src/downloader/invariants.rs
src/downloader/test/dialer.rs

`Dialer` is being removed from `iroh`
- `downloader::Dialer` is made private

refactor!: make Dialer trait private and inline iroh::dialer::Dialer

---

Cargo.lock
Cargo.toml
examples/connect/mod.rs

Update rcgen to 0.13 in examples
None

chore: Update rcgen to 0.13

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
Cargo.lock
Cargo.toml
deny.toml
examples/custom-protocol.rs
examples/hello-world-fetch.rs
examples/hello-world-provide.rs
examples/local-swarm-discovery.rs
examples/transfer.rs
src/cli.rs
src/downloader.rs
src/downloader/test.rs
src/get/db.rs
src/hash.rs
src/lib.rs
src/net_protocol.rs
src/rpc.rs
src/rpc/client/blobs.rs
src/rpc/proto/blobs.rs
src/store/bao_file.rs
src/store/fs.rs
src/store/fs/tables.rs
src/store/mem.rs
src/store/mutable_mem_storage.rs
src/ticket.rs
src/util/fs.rs

As `iroh_base::hash` and `iroh_base::ticket::BlobtTicket` are mainly `iroh-blobs` concerns they are moved into here.
This also updates to the latest `iroh@main` so 
- `AddrInfoOptions` has been removed
- MSRV is bumped to `1.81`
- `addr_options` on the cli is removed from the `share` call

feat: import iroh_base::ticket::BlobTicket and iroh_base::hash

---

Cargo.lock
Cargo.toml
deny.toml
examples/hello-world-fetch.rs
examples/local-swarm-discovery.rs
src/downloader/test.rs
src/hash.rs
src/rpc/client/blobs.rs
src/ticket.rs
src/util/fs.rs

feat!: update to iroh@0.30.0

---

README.md
examples/custom-protocol.rs
examples/hello-world-fetch.rs
examples/hello-world-provide.rs
examples/local-swarm-discovery.rs
examples/transfer.rs
src/net_protocol.rs
src/rpc.rs
src/rpc/client/blobs.rs
tests/blobs.rs
tests/gc.rs
tests/rpc.rs

It has been a footgun for a few users, including myself, to make sure to keep around the `LocalPool`. This changes the behaviour to construct a `LocalPool` and keep it around by default. If necessary, in the builder one can provide a custom handle, if there is the need for a custom pool.
- remove `net_protocol::Blobs::new`, use the builder instead
- remove the `LocalPoolHandle` argument from `net_protocol::Builder::build`

feat!: simplify LocalPool handling

---

README.md
deny.toml
src/store/fs.rs

- remove mention of using raw quinn, since that is no longer possible
- consistently use upper case for QUIC and BLAKE3
- eliminate mention of collections. Collections are just one of many special cases of hash sequences.
- remove mention of reexport that does not exist anymore
None
Note: the readme is also used from the iroh docs page. That is why I have a link to "this repository".

docs: Update readme

---

Cargo.lock
Cargo.toml
deny.toml

upgrade to `iroh@v0.33`, `quic-rpc@v0.18.2`, and `quic-rpc-derive@v0.18.2`

chore: upgrade to latest `iroh` and `quic-rpc`

---

Cargo.lock
Cargo.toml

Patch release to fix the panic when parsing a short hash string
None
Note: also fixes a panic when an oneshot receiver deep in the bowels of the quinn transport is being polled after completion.

chore: Release

---

src/hash.rs
src/rpc.rs
src/rpc/client/blobs/batch.rs
src/rpc/client/tags.rs
src/rpc/proto/tags.rs
src/store/fs.rs
src/store/mem.rs
src/store/readonly_mem.rs
src/store/traits.rs
src/util.rs
tests/gc.rs
tests/tags.rs

This makes the anemic tags api much more rich
- Tag deletion
- delete by range, by prefix, single item, or all 💣 
- Tag listing
- list by range, prefix or get single item
- Tag setting
- set a tag to a value
- Tag renaming
- atomic rename, just like for files
Breaks the RPC protocol and the store trait
RPC protocol:
- rpc::proto::tags::DeleteRequest now has from and to field
- rpc::proto::tags::DeleteRequest no longer has name field
- rpc::proto::tags::ListRequest now has from and to field
- rpc::proto::tags::ListRequest::all removed
- rpc::proto::tags::ListRequest::raw removed
- rpc::proto::tags::ListRequest::hash_seq removed
Store trait:
- store::traits::ReadableStore::tags now takes from and to
Question: should we enable the rpc feature flag by default? Given that the only way to get …

feat: Richer tags api

---

src/net_protocol.rs

A fix for https://github.com/n0-computer/iroh-blobs/issues/74 , allowing users of the Blobs protocol to once again provide configuration for the internally-used Downloader struct - both concurrency and retry options.
This PR exposes them through the Blobs Builder struct.
I haven't added tests, but this seems to work fine. I probably need tests for these methods to be a good OSS citizen ;)

feat: modify Downloader config through Blobs builder

---

Cargo.toml
src/lib.rs
src/rpc/client/tags.rs
src/store/fs.rs

Almost the entire friendly API of the crate is only available if the `rpc` feature flag is set. So this enables rpc by default to make the crate easier to use for beginners.
I also document feature flags in the module docs (should this instead be in README.md?) so people that need fewer deps know what to do.
None
Note: there is also a bugfix to the new tags API. The rename fn in the API was not actually using the shiny new atomic rename but just the multi-step rename. If we decide not to enable rpc by default I will move that change into a separate PR.

feat: Enable RPC by default

---

Cargo.lock
Cargo.toml

Update bao-tree dependency and get rid of iroh-blake3 dep
None
Note: the purpose of this is to be able to retire our blake3 fork. It should not change anything other than that.

chore: update bao-tree dependency and get rid of iroh-blake3 dep

---

src/rpc/client/blobs.rs

Add fn boxed to client so there is an easy way to get rid of the annoying type parameter
None
Do we also need this on tags and blobs client?

feat: boxed client

---

Cargo.toml
deny.toml

We had some issues with the latest redb using edition 2024. This restricts redb to the latest version that uses edition 2021.
None
Should we do a range restriction so people would get 2.4.1 if it gets released?

chore: Fix redb version to the latest version that uses edition 2021

---

Cargo.lock
Cargo.toml

Use latest bao-tree that fixes a bug when getting a short read
None
None

fix: use latest bao-tree

---

Cargo.lock
Cargo.toml
deny.toml
src/downloader.rs
src/downloader/get.rs
src/downloader/test.rs
src/metrics.rs
src/net_protocol.rs

Updates metrics tracking to the new non-global tracking.
Metrics are tracked per downloader. We already only track metrics within the downloader, so this was rather straightforward.
The tracking of request stats was changed to be tracked once the download task completes, as this seemed easier to me. Needs a careful review, but I think the change is sound (i.e. no change).
Depends on https://github.com/n0-computer/iroh/pull/3262
* `metrics::Metrics` now implements `MetricsGroup` from the recent  ìroh-metrics` release (TODO: fill in version after release)
* Metrics are no longer tracked into the `static_core` from `iroh-metrics`, but instead are tracked per `Downloder` and exposed via `Downloader::metrics`

refactor!: update to latest iroh-metrics version, use non-global metrics collection

---

Cargo.lock
Cargo.toml
README.md
deny.toml
examples/custom-protocol.rs
examples/discovery-local-network.rs
examples/hello-world-fetch.rs
examples/hello-world-provide.rs
examples/transfer.rs
src/rpc/client/blobs.rs
tests/gc.rs
tests/rpc.rs

- update`iroh` to 0.35
- update `quic-rpc` to 0.20
- update `iroh-base` to 0.35

chore: update to `iroh` v0.35

---

src/downloader.rs
src/downloader/test.rs
src/net_protocol.rs
tests/rpc.rs

Allow configuring the downloader when creating a blobs protocol handler
we don't allow passing in the entire downloader, but all config options.
`iroh_blobs::downloader::Downloader` now takes a `config: Config ` argument instead of `concurrency_limits: ConcurrencyLimits, retry_config: RetryConfig`. `Config` has two public field `concurrency_limits` and `retry_config`, so the migration is straightforward.
Otherwise there's only additions (a new method `downloader_config` on the `Blobs` constructor).

feat!: Allow configuring the downloader when creating a blobs protocol handler

---

Cargo.lock
Cargo.toml
deny.toml

This PR updates the following dependencies to use their main branches:
- `iroh` from `https://github.com/n0-computer/iroh.git`
- `irpc` from `https://github.com/n0-computer/irpc.git`
- `iroh-base` from `https://github.com/n0-computer/iroh.git`

chore: add patch for `iroh` dependencies

---

Cargo.lock
Cargo.toml

Lose some non-used deps. Futures-buffered is reexported by n0-future, as I learned yesterday
None
None

chore: Remove unused dependencies

---

examples/transfer.rs
src/api/downloader.rs

Revives the [old transfer example](https://github.com/n0-computer/iroh-blobs/blob/8a975ecda8bca5e8988db911857012e6817b456e/examples/transfer.rs) so we can use it on the https://www.iroh.computer/docs/quickstart page
Also fixes a bug.

docs: Update the transfer example to iroh 0.90

---

examples/transfer.rs

Was broken by https://github.com/n0-computer/iroh-blobs/pull/112
None

fix: fix connect example

---

Cargo.toml

This updates the repository link from the old/temporary `blobs2` repo to `iroh-blobs`.

docs: fix repo link in Cargo.toml

---

.github/workflows/ci.yaml
src/api.rs
src/api/blobs.rs
src/api/blobs/reader.rs
src/store/fs.rs

Add an api for reading and seeking a blob using tokio::io::AsyncRead and tokio::io::AsyncSeek
Changes api::blobs::ExportRangesProgress::stream to be non-async - it does not have to be!
Note: the entire machinery of seek and read is horribly undocumented regarding the non happy case. So I went with the following approach: if you ever drop a future of either seek or read before completing, the reader becomes poisioned and will never work again, you have to grab a new one, which is cheap.
This bypasses the whole question about what to do if somebody calls x without having completed y, and in normal usage you should never notice this.

feat: Read and seek

---

Cargo.lock
Cargo.toml
examples/common/mod.rs
examples/custom-protocol.rs
examples/get-blob.rs
examples/mdns-discovery.rs
examples/request.rs
examples/transfer.rs

Add back the examples that were removed when moving from 0.35 to 0.9x.
None
How much should we bikeshed the progress reporting in the examples, using console and indicatif crates? On the one hand it is nice, on the other hand it makes the examples more complex.
I think we might put basic progress display for import, download and export into the util crate. But I think it would be nice if we could get by without the `--features exampes` feature flag for most or all examples, so maybe not use console and indicatif so we don't have to have it as dev dependencies.
I changed the transfer example to use clap like the other examples. I hope you don't mind, @matheus23.
Implements https://github.com/n0-computer/iroh-blobs/issues/120
Implements https://github.com/n0-computer/iroh-blobs/issues/117

docs: Revive 0.35 examples

---

Cargo.lock
Cargo.toml
src/api/blobs/reader.rs
src/api/downloader.rs
src/api/remote.rs
src/get/request.rs
src/lib.rs
src/protocol.rs
src/protocol/range_spec.rs
src/store/fs.rs
src/store/mem.rs
src/store/readonly_mem.rs
src/util.rs
src/util/connection_pool.rs

Replaces the somewhat hackish connection pool with the one from https://github.com/n0-computer/iroh-experiments/pull/36 that was battle tested more.
None
Q: Expose the conn pool here?
Note: There is a nice list of possible extensions, but I think it is probably best to first get the basic version in.
Extensions would be `async fn ban(node_id: NodeId, duration: Option<Duration>)`, bans the node for a time, or for as long as the conn pool lives if duration is set to None.
A way to observe pool stats so users know when to schedule new downloads without having to try.

refactor: Replace connection pool

---

examples/limit.rs
src/provider.rs
src/provider/events.rs
src/tests.rs

For some reason we can't get the node_id for 0rtt connections. Blobs does not use 0rtt, but it might in the future. So we don't have the node_id in all cases when we need to create a ClientConnected event.
See https://github.com/n0-computer/iroh/issues/3123
No additional breaking changes compared to the last published version, since the ClientConnected event is new.
Question: should we add some more stuff to the ClientConnected event since we might not have the node id? Socket addrs or something?

feat: Make node_id in ClientConnected optional

---

src/store/fs.rs

We don't want to move, but to copy in that case.
We also update the db, but limit the max number of external paths to MAX_EXTERNAL_PATHS
This fixes a regression from blobs 0.35 regarding ExportMode::TryReference
Fixes https://github.com/n0-computer/sendme/issues/103
None

fix: Export try reference bugfix

---

Cargo.lock
Cargo.toml
deny.toml

Upgrade deps in prep for 0.94.0 release

chore: upgrade `iroh`, `iroh-base`, `irpc`, `tracing-subscriber`, and `n0-snafu`

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
Cargo.lock
Cargo.toml
src/store/fs/meta.rs

The recently released redb v3 has incompatible changes to the database format. The recommended upgrade procedure is to upgrade the database with `Database::upgrade` on redb v2.6+. The upgrade has to be done on redb v2, not v3. See https://github.com/cberner/redb/blob/master/CHANGELOG.md#removes-support-for-file-format-v2.
This updates redb to 2.6 and performs the upgrade when opening the database. Calling upgrade on an already upgraded database is a no-op.
With this merged in the next release, we can then update redb to v3 in the version after.

feat: upgrade database to redb v3 compatible format
